<?php /* This file is autogenerated. */
return [
    'main.message.hello' => [
        'Hello',
    ],

    'main.message.hello_multiline' => [
        'Hello!
How are you?',
    ],

    'main.message.hello_$' => [
        'Hello, [:name:]',
    ],

    'main.message.hello_$$' => [
        'Hello, [:name1:] and [:name2:]',
    ],

    'main.title.plural' => [
        'Item',
        'Items',
    ],

    'main.title.plural_multiline' => [
        'Item
Subitem',
        'Items
Subitems',
    ],

    'main.choice.apple' => [
        '[:choice:] apple',
        '[:choice:] apples',
    ],
];
